const ActionTypes = {
    // ITEMS
    ITEM_RECEIVE_ITEMS: 'ITEM_RECEIVE_ITEMS',
    ITEM_FETCH_ITEMS: 'ITEM_FETCH_ITEMS',
    ITEM_SELECT_ITEM: 'ITEM_SELECT_ITEM',

    // LEADERBOARD
    LEADERBOARD_FETCH_LEADERS: 'LEADERBOARD_FETCH_LEADERS',
    LEADERBOARD_RECEIVE_LEADERS: 'LEADERBOARD_RECEIVE_LEADERS',
    LEADERBOARD_SELECT_LEADER: 'LEADERBOARD_SELECT_LEADER',

    // USE ITEMS
    USE_ITEM_USE: 'USE_ITEM_USE',
    USE_ITEM_RESPONSE: 'USE_ITEM_RESPONSE',
};

export default ActionTypes;