const ActionTypes = {
    // ITEMS
    ITEM_RECEIVE_ITEMS: 'ITEM_RECEIVE_ITEMS',
    ITEM_FETCH_ITEMS: 'ITEM_FETCH_ITEMS',

    // LEADERBOARD
    LEADERBOARD_FETCH_LEADERS: 'LEADERBOARD_FETCH_LEADERS',
    LEADERBOARD_RECEIVE_LEADERS: 'LEADERBOARD_RECEIVE_LEADERS',
};

export default ActionTypes;